FROM maven:3.9.9-eclipse-temurin-11 AS build

WORKDIR /workspace
COPY pom.xml ./
COPY src src
RUN --mount=type=cache,target=/root/.m2 \
    mvn -B -ntp package \
      -DskipTests \
      -Dspring-javaformat.skip=true \
      -Dcheckstyle.skip=true \
      -Djacoco.skip=true

# Base antigua intencional para demostrar el bloqueo del gate Image Security.
FROM eclipse-temurin:11.0.17_8-jre-focal

RUN groupadd --system clinic && useradd --system --gid clinic clinic
WORKDIR /app
COPY --from=build /workspace/target/spring-petclinic-2.6.0-SNAPSHOT.jar app.jar
USER clinic
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
